version: 2
jobs:
  build:

    working_directory: ~/employees-REST-spring-boot

    docker:
      - image: circleci/openjdk:11.0.1-jdk

    steps:

      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/employees-RESTAPI-0.0.1-SNAPSHOT.jar