version: 2
jobs:
  build:

    working_directory: ~/employees-REST-spring-boot

    docker:
      - image: circleci/openjdk:11.0.1-jdk
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circleci_test

    steps:

      - checkout

      - restore_cache:
          key: employees-REST-spring-boot-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: employees-REST-spring-boot-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/employees-RESTAPI-0.0.1-SNAPSHOT.jar